test: add unit tests for rpc/v1/publish.go
matheusmosca/walrus pull request #35
Opened 2021-10-05 06:44 UTC by Smelton01

This pr adds unit test for rpc/v1/publish.go.
Addresses issue #31

2021-10-10 01:22 UTC, matheusmosca requested changes
Hi @Smelton01! Your pull request looks nice but I'll ask for some changes.
- You're just asserting the errors, could you also assert the gRPC status code from the response?
- You should've mock the [UseCase interface](https://github.com/matheusmosca/walrus/blob/main/domain/usecases/usecase.go#L24) and not the Repository. It would even turn this task simpler. To create the mock you just need to add a `go:generate comment` as shown below and run `make generate`.
```go
//go:generate moq -fmt goimports -out usecase_mock.go . UseCase:UseCaseMock
type UseCase interface {
  Publish(ctx context.Context, message vos.Message) error
  Unsubscribe(ctx context.Context, subscriberID vos.SubscriberID, topicName vos.TopicName) error
  Subscribe(ctx context.Context, topicName vos.TopicName) (chan vos.Message, vos.SubscriberID, error)
  ListTopics(ctx context.Context) ([]entities.Topic, error)
}
```

2021-10-10 01:22 UTC, matheusmosca commented on rpc/v1/publish_test.go
> +}
Could you remove those definitions from the global scope? Actually, I Think these definitions are not necessary

2021-10-10 01:22 UTC, matheusmosca commented on rpc/v1/publish_test.go
> +		message pb.Message
The CI lint is not passing because you are using `pb.Message` here and copying it on each for iteration. you can replace it with a `vos.Message` type. So you would do something like this:
```go
publishRequest := &pb.PublishRequest{
	Message: &pb.Message{
		Topic:       tt.args.message.TopicName.String(),
		PublishedBy: tt.args.message.PublishedBy,
		Body:        tt.args.message.Body,
	},
}

_, err = client.Publish(tt.args.ctx, publishRequest)
```

2021-10-10 01:27 UTC, matheusmosca commented on rpc/v1/publish_test.go
> +		want      []byte
You can remove those fields, the idea of this test is to check the status code and the error from the gRPC response. You do not need the `beforeRun` function because you should mock the UseCase.

2021-10-17 05:32 UTC, Smelton01 commented
@matheusmosca thank you for the detailed feedback, I fixed the tests according to your comments, please have a look and let me know If I need to improve anything else.

2021-10-27 01:51 UTC, Smelton01 commented
@matheusmosca I don't mean to rush you or anything but I would really appreciate getting a review on this PR sometime soon, I am counting on it for my hacktoberfeat stars

2021-10-27 02:26 UTC, matheusmosca requested changes
Hi @Smelton01, Your PR is not passing on CI. You'll need to simplify this code to make it pass on lint check. Before pushing new commits, make sure your code is passing in all checks by doing `make lint` and `make test-coverage`.

2021-10-27 02:26 UTC, matheusmosca commented on rpc/v1/publish_test.go
> +		wantErr *grpcError
Could your replace this wantErr with this? You can remove grpcError as well
```suggestion
		wantErr error
                wantCode codes.Code
```

2021-10-27 02:26 UTC, matheusmosca commented on rpc/v1/publish_test.go
> +			wantErr: &grpcError{},
```suggestion
			wantErr: nil,
```

2021-10-27 02:26 UTC, matheusmosca commented on rpc/v1/publish_test.go
> +			assert.NoError(t, err)
Your PR are not passing on CI due to complexity, you need to simplify this code
```suggestion
                      assert.ErrorIs(t, err, tt.wantErr)
			if tt.wantErr != nil {
				gotCode, _ := status.FromError(err)
				assert.Equal(t, tt.wantCode, gotCode)
				return
			}
```

2021-10-27 02:26 UTC, matheusmosca commented on rpc/v1/publish_test.go
> +			ctx := context.Background()
Why are you declaring a new ctx here? You can access the test's context by doing tt.args.ctx

2021-10-27 02:26 UTC, matheusmosca commented on rpc/v1/publish_test.go
> +		topicName vos.TopicName
Why did you create this struct? the "fields" should have the use-case mock response

2021-10-27 02:26 UTC, matheusmosca commented on rpc/v1/publish_test.go
> +			}
Could you define the mock in each element in the slice of tests? For example, on the test case where you want to test if a topic was not found:

```go
{
			name: "nonexistent topic should return error",
			args: args{
				ctx: context.Background(),
				message: vos.Message{
					TopicName:   "elephant",
					PublishedBy: "noone",
					Body:        []byte("bye world"),
				},
			},
			fields: fields{
				usecaseMock: &usecases.UseCaseMock{
				    PublishFunc: func(ctx context.Context, message vos.Message) {
						return entities.ErrTopicNotFound
				    },
                                },
			},
			wantCode: codes.NotFound,
			wantErr: entities.ErrTopicNotFound,
		},
```

2021-10-28 04:20 UTC, matheusmosca commented on rpc/v1/publish_test.go
> +					Body:        []byte("helloorld"),
```suggestion
					Body:        []byte("hello world"),
```

2021-10-28 04:22 UTC, matheusmosca approved these changes
Thanks, @Smelton01! Your pull request looks nice :rocket:

2021-10-28 04:24 UTC, merged